name: build-test-deploy

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.2.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          useConfigFile: true
          updateProjectFiles: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build -c Release src/ddd-seed/

      - name: Test
        run: ./test.sh -t

      - name: Pack
        if: ${{ startsWith(github.ref, 'refs/heads/pre-release') || startsWith(github.ref, 'refs/heads/release') }}
        run: |
          dotnet pack -c Release \
          -p:PackageVersion=$pv \
          -p:AssemblyVersion=$av \
          -p:FileVersion=$fv \
          '-p:InformationalVersion=$iv-$sha' \
          --no-build src/ddd-seed/
        env:
          pv: ${{ steps.gitversion.outputs.semVer }}
          av: ${{ steps.gitversion.outputs.assemblySemVer }}
          fv: ${{ steps.gitversion.outputs.assemblySemFileVer }}
          iv: ${{ steps.gitversion.outputs.fullSemVer }}
          sha: ${{ steps.gitversion.outputs.shortSha }}

      - name: Push package to nuget
        if: ${{ startsWith(github.ref, 'refs/heads/pre-release') || startsWith(github.ref, 'refs/heads/release') }}
        run: |
          dotnet nuget push **/*.nupkg \
            --skip-duplicate \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            --api-key ${{ secrets.GITHUB_TOKEN }}
