name: Nuget Package Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Build with dotnet
        run: dotnet build -c Release ddd-seed/
      - name: Test with dotnet
        run: dotnet test ddd-seed/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Pack nuget Package
        run: dotnet pack -c Release ddd-seed/
      - name: Add Github Nuget source
        run: dotnet nuget add source https://nuget.pkg.github.com/japurcell/index.json -n github -u japurcell -p ${{secrets.GITHUB_TOKEN}}
      - name: Push package to nuget
        run: dotnet nuget push **/*.nupkg --source "github" --skip-duplicate
