name: Nuget Package Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Build with dotnet
        run: dotnet build -c Release ddd-seed/

      - name: Test with dotnet
        run: dotnet test ddd-seed/

      - name: Pack
        run: dotnet pack -c Release -o finalpackage --no-build

      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: nupkg
          path: finalpackage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@master
        with:
          name: nupkg

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://nuget.pkg.github.com/japurcell/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push package to nuget
        run: dotnet nuget push nupkg/*.nupkg --skip-duplicate
