name: Nuget Package Deploy

on:
  push:
    branches: [ release/** ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
          versionSpec: '5.2.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with dotnet
        run: dotnet build -c Release ddd-seed/

      - name: Test with dotnet
        run: ./test.sh -t

      - name: Pack
        run: |
          dotnet pack -c Release \
          -p:PackageVersion=$pv \
          -p:AssemblyVersion=$av \
          -p:FileVersion=$fv \
          '-p:InformationalVersion=$iv-$sha' \
          --no-build ddd-seed/
        env:
          pv: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
          av: ${{ steps.gitversion.outputs.assemblySemVer }}
          fv: ${{ steps.gitversion.outputs.assemblySemFileVer }}
          iv: ${{ steps.gitversion.outputs.fullSemVer }}
          sha: ${{ steps.gitversion.outputs.shortSha }}

      - name: Push package to nuget
        run: dotnet nuget push **/*.nupkg --skip-duplicate
